
name: HuggingFace Space Sync

on:
  push:
    branches:
      - 'main'
      - 'feature/hf-space-sync'
    paths:
      - gradio/**
      - .github/workflows/hf-space-sync.yml

jobs:
  push-hf-space:
    name: Push source code to HuggingFace
    runs-on: ubuntu-latest
    env:
      # Fix BUG https://github.com/huggingface/huggingface_hub/issues/4571
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Sync to HuggingFace
        uses: xiaoyao9184/huggingface-sync-action@5d6858f36500be81bd63443f6138b3d5a14d46ea
        with:
          huggingface_repo_id: '${{ secrets.HF_USERNAME }}/reverse-from-synthid'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false
          space_sdk: 'gradio'
          subdirectory: 'gradio'
          include_readme: true
          generate_message: true
