
name: HuggingFace Space Sync

on:
  push:
    branches:
      - 'main'
      - 'feature/hf-space-sync'
    paths:
      - gradio/**
      - space/**
      - scripts/link-gradio.sh
      - .github/workflows/hf-space-sync.yml

jobs:
  push-hf-space:
    name: Push source code to HuggingFace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Prepare Space directory
        run: bash scripts/link-gradio.sh --mode copy space/

      - name: Sync to HuggingFace
        uses: xiaoyao9184/huggingface-sync-action@v0.0.5-0.0.2
        with:
          huggingface_repo_id: '${{ secrets.HF_USERNAME }}/reverse-from-synthid'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false
          space_sdk: 'gradio'
          subdirectory: 'space'
          include_readme: true
          generate_message: true
